##############################################
#                Video Output                #
##############################################
vo=gpu
gpu-api=opengl
gpu-context=wayland
hwdec=auto-safe
scale=bilinear

##############################################
#               YouTube-DLP                  #
##############################################
ytdl-format=bestvideo[height<=?1080]+bestaudio/best
script-opts=ytdl_hook-ytdl_path=yt-dlp
ytdl-raw-options=cookies-from-browser=chromium,ignore-config=,sub-langs="ja-orig,ja,jpn,jp,en",write-sub=,write-auto-sub=
hwdec=auto-safe

##############################################
#             Subtitle Settings              #
##############################################
sub-font="Noto Sans Mono CJK JP 12"
sub-font-size=50

sub-color="#ffffff"               # White font
sub-border-color="#000000"        # Black border
sub-border-size=2.0
sub-shadow-offset=1
sub-shadow-color="#000000"

sub-pos=99                        # Bottom center
slang=jp,jpn,ja,ja-orig                      # Preferred subtitle languages
sub-auto=fuzzy                    # Load external & embedded
sub-visibility=yes  

sub-ass-override=force            # Force custom styling over embedded .ass

##############################################
#               Audio Settings               #
##############################################
aid=auto
alang=ja,en,jpn,jp,ja-orig

volume=50
volume-max=300

audio-device=auto
audio-samplerate=48000
audio-channels=stereo
autosync=30
audio-file-auto=fuzzy

##############################################
#            Screenshots Settings            #
##############################################
screenshot-directory=~/Pictures/mpv_shots
screenshot-format=png

##############################################
#            General Playback                #
##############################################
save-position-on-quit=yes
osd-bar=no
cache-pause=no
autofit-larger=100%x100%
geometry=50%:50%



